### ISSUE TITLE
Please can you provide documentation regarding gemini model connection.

### ISSUE THREAD

**Issue by patilpriyadarshini** [BCG-X-Official/artkit#58] opened 2024-07-25 09:21 UTC
As the https://bcg-x-official.github.io/artkit/user_guide/introduction_to_artkit/connecting_to_genai_models.html#Google link is empty with no connection result.

**Comment by seanggani** [comment] 2024-07-29 19:58
Closing this issue as it is a duplicate of https://github.com/BCG-X-Official/artkit/issues/59

**Closed as completed by seanggani** 2024-07-29 19:58 UTC
